version: '3'

services:
  app:
    image: gedasfx/thehunt:0.1.0
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      
  redis:
    image: redislabs/rejson:latest
    restart: always
    ports:
      - "6379:6379"
