version: "3.8"

services:
  app:
    image: ghcr.io/gedasfx/thehunt:1
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "TOKEN_GOES_HERE"
    volumes:
      - ./data/google.json:/app/google.json:ro
      - ./data/db:/app/data
